---
title: "Grade Report HW1"
subtitle: Aung, Thandar
output: html_document
---

## Overall Grade: 96/110

### Quality of report: 9/10

-   Is the homework submitted (git tag time) before deadline (Due Sep 23, 2020 @ 11:59PM)?

    No. `2020-09-24 19:52:50`. (-1 pt)

-   Is the final report in a human readable format html? 

    Yes. `html`.

-   Is the report prepared as a dynamic document (R markdown) for better reproducibility?

    Yes. `Rmd`.

-   Is the report clear (whole sentences, typos, grammar)? Do readers have a clear idea what's going on and how are results produced by just reading the report? 

    Yes. 
	  
### Correctness and efficiency of solution: 49/60

-   Q1 (10/10)

-   Q2 (16/20) 
    
    - Q2.2. More efficient is to write a function. (-1 pt)
```{bash, eval = F}
awk '
{chrno[$1]++;} 
END{ for (c in chrno) print "chr.", c, "has", chrno[c], "SNPs"}'  /home/bios-cph511-data/hw1/merge-geno.bim
```

    - Q2.3. Typo in your code. Should be 894 SNPs. (-1 pt)
    
    - Q2.4. Outputs are not correct. (-2 pts)

```{bash, eval = F}
awk -v sex="" -v paid="" -v maid="" '
{OFS = ","} 
{if ($5==1) sex="M"; else sex="F"} 
{if ($3==0) paid=""; else paid=substr($3, 5, 11)} 
{if ($4==0) maid=""; else maid=substr($4, 5, 11)} 
{print $1, substr($2, 5, 11), paid, maid, sex, ""}
'  /home/bios-cph511-data/hw1/merge-geno.fam > mendel_ped.txt
```

-   Q3 (25/30) 
    
    The code to collect results from simulation seems to have bug. The results were off. (-5 pts)
    
  
    
### Usage of Git: 8/10

-   Are branches (`master` and `develop`) correctly set up? Is the hw submission put into the `master` branch?

    Yes.

-   Are there enough commits? Are commit messages clear?  

    Yes. 
   
-   Is the hw1 submission tagged? 

    Yes. 

-   Are the folders (`hw1`, `hw2`, ...) created correctly? 

    No.  Please set up correct folders for hw2, hw3, etc. (-1 pt)
  
-   Do not put a lot auxiliary files into version control. 

	  Do not upload simulation output to git. (-1 pt)


### Reproducibility: 10/10

-   Are the materials (files and instructions) submitted to the `master` branch sufficient for reproducing all the results? Just click the `knit` button will produce the final `html` on teaching server? 

    I can knit your code, but results contains mistakes. 
  	

-   If necessary, are there clear instructions, either in report or in a separate file, how to reproduce the results?

    Yes.

### R code style: 20/20
-   [Rule 3.](https://google.github.io/styleguide/Rguide.xml#linelength) The maximum line length is 80 characters. 


-   [Rule 4.](https://google.github.io/styleguide/Rguide.xml#indentation) When indenting your code, use two spaces.

-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.). 


-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Do not place a space before a comma, but always place one after a comma. 

#### Violations





